Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue user-management-vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebEC2InstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - LabRole  

Outputs:
  WebSecurityGroupId:
    Description: Security Group to allow us to http and ssh into an EC2 instance
    Value: !GetAtt WebServerSecurityGroup.GroupId
    Export: 
      Name: !Sub "${AWS::StackName}-WebSecurityGroupId"

  WebEC2InstanceProfile:
    Description: Role that will allow EC2 to communicate with other AWS Services such as CloudWatch and S3
    Value: !Ref WebEC2InstanceProfile
    Export: 
      Name: !Sub "${AWS::StackName}-WebEC2InstanceProfile"

