- name: My first play
  hosts: web
  tasks:
   - name: Check that you can connect (GET) to a page and it returns a status 200
     ansible.builtin.uri:
        url: http://52.54.104.198:8080/UserManagement